export const FETCH_SHIPPING_OPTIONS = 'FETCH_SHIPPING_OPTIONS';
export const FETCH_SHIPPING_OPTION = 'FETCH_SHIPPING_OPTION';
export const ADD_SHIPPING_OPTION = 'ADD_SHIPPING_OPTION';
export const UPDATE_SHIPPING_OPTION = 'UPDATE_SHIPPING_OPTION';
export const DELETE_SHIPPING_OPTION = 'DELETE_SHIPPING_OPTION';
export const SET_SHIPPING_OPTIONS_LOADING = 'SET_SHIPPING_OPTIONS_LOADING';
export const SET_SHIPPING_FORM_ERRORS = 'SET_SHIPPING_FORM_ERRORS';
export const RESET_SHIPPING_FORM = 'RESET_SHIPPING_FORM';
